name: CI

on:
  push:
  pull_request:


jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.11

      - name: Install Poetry 2.1.3
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.1.3

      - name: Install dev dependencies (linters, type checkers)
        run: poetry install --no-root --with dev

      - name: Run Black
        run: poetry run black --check .

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run Mypy
        run: poetry run mypy .

      - name: Run Vulture
        run: poetry run vulture stroke_predictor

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: code-quality

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.11

      - name: Install Poetry 2.1.3
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.1.3

      - name: Install all dependencies
        run: poetry install --no-root

      - name: Run tests with pytest
        run: poetry run pytest

  docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.11

      - name: Install Poetry 2.1.3
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.1.3

      - name: Install docs dependencies
        run: poetry install --no-root --with docs

      - name: Build MkDocs site
        run: poetry run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
